language: ruby
rvm:
- 2.4.0
services:
- postgresql
email: true
cache: bundler
install:
- gem update --system
- bin/bundle install --jobs=3 --retry=3 --deployment --without production
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- bin/rspec
- bin/rubocop
